version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'hourly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'hourly'
