name: Unit Tests
on: 'push'

jobs:
  tag:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          memory_limit: 256M
