# Based on https://github.com/wp-cli/scaffold-command/blob/f9bad3dd7224d5684d950d31c486df70905e386f/templates/plugin-github.mustache
name: WordPress Test

on:
  # Run on pushes to select branches and on all pull requests.
  push:
    branches:
      - master
      - develop
      - 'release/**'
      - 'hotfix/[0-9]+.[0-9]+*'
      - 'feature/**'
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#env:
#  WP_TESTS_DIR: /tmp/wp-tests/wordpress-tests-lib
#  WP_CORE_DIR: /tmp/wp-tests/wordpress

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.4]
        wordpress-version: [latest]
    services:
      sendria:
        image: msztolcman/sendria:v2.2.2.0
        ports:
          - 1080:1080
          - 1025:1025

    steps:
      - name: Set up MySql
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '5.7'
          root-password: 'root'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer, cs2pr

      - name: Test sendria connection
        run: curl -LI localhost:1080

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set script execution permission
        run: |
          chmod +x bin/install-wp-tests.sh

      - name: Install WordPress test suite
        run: |
          cd bin
          ./install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wordpress-version }}
          chmod -R 755 /tmp/wordpress

      - name: Run Composer Install
        run: composer update --no-interaction && composer install --no-interaction

      - name: run syntax check
        run: composer lint

      - name: run unit tests
        run: vendor/bin/phpunit --config=phpunit-unit.xml

      - name: run integration tests
        run: vendor/bin/phpunit --config=phpunit-integration.xml
